# Generated by Django 3.2.18 on 2023-04-27 13:25

import django.core.validators
from django.db import migrations, models
import todo_app.common.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), todo_app.common.custom_validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), todo_app.common.custom_validators.validate_only_letters]),
        ),
    ]
